/**
 * Sync `@app/shared` brand into Tauri shell configs (JSON / Cargo / Rust)
 * and the published macOS installer script.
 * Run after editing `packages/shared/src/brand.ts` (`npm run sync:brand`).
 * Desktop/mobile beforeDev/beforeBuild also invoke this.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { brand } from "../packages/shared/src/brand.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Escape a value for a TOML basic string (`"..."`). */
function tomlBasicString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function writeJson(path, data) {
  writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`);
}

/** Patch only `description` — leave `authors` alone (not product identity). */
function patchCargoDescription(path, description) {
  let text = readFileSync(path, "utf8");
  text = text.replace(/^description = ".*"$/m, `description = ${tomlBasicString(description)}`);
  writeFileSync(path, text);
}

function patchShellAssignment(path, name, value) {
  const text = readFileSync(path, "utf8");
  const re = new RegExp(`^${name}=.*$`, "m");
  if (!re.test(text)) {
    throw new Error(`${name}= line not found in ${path}`);
  }
  writeFileSync(path, text.replace(re, `${name}=${JSON.stringify(value)}`));
}

const desktopConfPath = resolve(root, "apps/desktop/src-tauri/tauri.conf.json");
const desktopConf = JSON.parse(readFileSync(desktopConfPath, "utf8"));
desktopConf.productName = brand.displayName;
desktopConf.app.windows[0].title = brand.displayName;
writeJson(desktopConfPath, desktopConf);

const mobileConfPath = resolve(root, "apps/mobile/src-tauri/tauri.conf.json");
const mobileConf = JSON.parse(readFileSync(mobileConfPath, "utf8"));
mobileConf.productName = brand.displayName;
mobileConf.app.windows[0].title = brand.displayName;
writeJson(mobileConfPath, mobileConf);

patchCargoDescription(
  resolve(root, "apps/desktop/src-tauri/Cargo.toml"),
  `${brand.displayName} desktop shell`,
);
patchCargoDescription(
  resolve(root, "apps/mobile/src-tauri/Cargo.toml"),
  `${brand.displayName} iOS shell`,
);

const brandRs = `//! Generated by \`scripts/sync-brand.mjs\` — do not edit by hand.
//! Source of truth: \`packages/shared/src/brand.ts\`.

pub const DISPLAY_NAME: &str = ${JSON.stringify(brand.displayName)};
`;
writeFileSync(resolve(root, "apps/desktop/src-tauri/src/brand.rs"), brandRs);

const installScript = resolve(root, "scripts/install-macos.sh");
patchShellAssignment(installScript, "BRAND_NAME", brand.displayName);
patchShellAssignment(installScript, "ARTIFACT_BASENAME", brand.desktopArtifactBasename);

console.log(
  `[sync-brand] synced displayName=${JSON.stringify(brand.displayName)} artifact=${JSON.stringify(brand.desktopArtifactBasename)}`,
);
