/**
 * Sync `@app/shared` brand into Tauri shell configs (JSON / Cargo / Rust)
 * and the published macOS installer script.
 * Run after editing `packages/shared/src/brand.ts` (`npm run sync:brand`).
 * Desktop/mobile beforeDev/beforeBuild also invoke this.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { brand } from "../packages/shared/src/brand.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Escape a value for a TOML basic string (`"..."`). */
function tomlBasicString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function writeJson(path, data) {
  writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`);
}

function patchCargoToml(path, { description, authors }) {
  let text = readFileSync(path, "utf8");
  text = text.replace(/^description = ".*"$/m, `description = ${tomlBasicString(description)}`);
  text = text.replace(/^authors = \[".*"\]$/m, `authors = [${tomlBasicString(authors)}]`);
  writeFileSync(path, text);
}

function patchBrandNameAssignment(path) {
  const text = readFileSync(path, "utf8");
  if (!/^BRAND_NAME=/m.test(text)) {
    throw new Error(`BRAND_NAME= line not found in ${path}`);
  }
  writeFileSync(
    path,
    text.replace(/^BRAND_NAME=.*$/m, `BRAND_NAME=${JSON.stringify(brand.displayName)}`),
  );
}

const desktopConfPath = resolve(root, "apps/desktop/src-tauri/tauri.conf.json");
const desktopConf = JSON.parse(readFileSync(desktopConfPath, "utf8"));
desktopConf.productName = brand.displayName;
desktopConf.app.windows[0].title = brand.displayName;
writeJson(desktopConfPath, desktopConf);

const mobileConfPath = resolve(root, "apps/mobile/src-tauri/tauri.conf.json");
const mobileConf = JSON.parse(readFileSync(mobileConfPath, "utf8"));
mobileConf.productName = brand.displayName;
mobileConf.app.windows[0].title = brand.displayName;
writeJson(mobileConfPath, mobileConf);

patchCargoToml(resolve(root, "apps/desktop/src-tauri/Cargo.toml"), {
  description: `${brand.displayName} desktop shell`,
  authors: brand.displayName,
});
patchCargoToml(resolve(root, "apps/mobile/src-tauri/Cargo.toml"), {
  description: `${brand.displayName} iOS shell`,
  authors: brand.displayName,
});

const brandRs = `//! Generated by \`scripts/sync-brand.mjs\` — do not edit by hand.
//! Source of truth: \`packages/shared/src/brand.ts\`.

pub const DISPLAY_NAME: &str = ${JSON.stringify(brand.displayName)};
`;
writeFileSync(resolve(root, "apps/desktop/src-tauri/src/brand.rs"), brandRs);

patchBrandNameAssignment(resolve(root, "scripts/install-macos.sh"));

console.log(`[sync-brand] synced displayName=${JSON.stringify(brand.displayName)}`);
